name: deploy
on:
  pull_request:
    branches:
      - '**'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: package-lock.json

      # Lintとテストの実行
      - name: npm install, build, and test
        run: |
          npm ci
          npm run build -- --configuration=production

      # デプロイ
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_BENATON_JAPAN }}'
          projectId: benaton-japan
          target: benaton-japan
